### ISSUE TITLE
Assistant

### ISSUE THREAD

**Issue by Syrup** [levina-lab/VeezMusic#28]
I'm confused about assistant at config vars does the assistant bot have to contain code? or not? or even that is not a bot?
that's all my question

**Comment by levina-lab** [comment]
can you explain it with more specified info again ?

**Comment by Syrup** [comment]
in config vars there is variable ASSISTANT_NAME and what is it supposed to contain?

**Comment by levina-lab** [comment]
@Syrup var ASISSTANT_NAME fill with your 2nd telegram account username without @, is used for the assistant userbot

**Comment by Syrup** [comment]
means is it not a bot?

**Comment by levina-lab** [comment]
@Syrup no

**Comment by Syrup** [comment]
ah, ok i got it thank you
